# Generated by Django 4.0.4 on 2022-07-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0002_alter_questao_pontuacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulado',
            name='pont_total',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
