# Generated by Django 4.0.4 on 2022-07-29 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0003_alter_simulado_pont_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulado',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulado.usuario'),
        ),
    ]
